//! ARIA-tree snapshot decoder + `@eN` element-ref minting.
//!
//! Snapshot format is a compact text representation, NOT a raw DOM dump.
//! Hidden + non-interactive nodes are excluded from ref minting to keep the
//! tool surface token-efficient. Refs are stable PER SNAPSHOT — every fresh
//! `Snapshot` op re-mints `@e1`, `@e2`, ...
//!
//! Design §5.16: ARIA-tree-first. Decoder accepts a fixture JSON tree
//! (the shape returned by Camoufox / CDP `Accessibility.getFullAXTree`) and
//! returns a flat sequence of refs paired with their compact text lines.

use serde::{Deserialize, Serialize};

/// Element ref `@eN`. Stable PER snapshot — regenerated by each `Snapshot` op.
#[derive(Debug, Clone, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub struct ElementRef(String);

impl ElementRef {
    pub fn new(id: impl Into<String>) -> Self {
        let s = id.into();
        // Accept both "@e1" and "e1" inputs — strip the prefix if present.
        let bare = s.strip_prefix('@').unwrap_or(&s).to_string();
        Self(bare)
    }

    pub fn as_str(&self) -> &str {
        &self.0
    }

    /// `@eN` form (the way the LLM sees it on the wire).
    pub fn display(&self) -> String {
        format!("@{}", self.0)
    }
}

/// One node in the decoded ARIA tree.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AriaNode {
    pub element_ref: ElementRef,
    pub role: String,
    pub name: String,
    /// Optional ancillary info (e.g. value for inputs, state for checkboxes).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub value: Option<String>,
    #[serde(default)]
    pub children: Vec<AriaNode>,
}

/// Full snapshot of a page's interactive ARIA tree, paired with the compact
/// text representation that gets shown to the LLM.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AriaSnapshot {
    /// Snapshot id (monotonic per-session). Future refs `@eN` are only
    /// valid against the latest snapshot id.
    pub snapshot_id: u32,
    pub url: String,
    pub title: String,
    /// Flat ref list — `nodes[i].element_ref` corresponds to `@e{i+1}`.
    pub nodes: Vec<AriaNode>,
    /// Compact text representation shown to the LLM.
    pub text: String,
}

impl AriaSnapshot {
    pub fn empty() -> Self {
        Self {
            snapshot_id: 0,
            url: String::new(),
            title: String::new(),
            nodes: Vec::new(),
            text: String::new(),
        }
    }

    /// Resolve `@eN` against this snapshot. Returns `None` if not found.
    pub fn resolve(&self, r: &ElementRef) -> Option<&AriaNode> {
        self.nodes.iter().find(|n| n.element_ref == *r)
    }
}

/// Raw input to the decoder — the shape returned by Camoufox /
/// CDP `Accessibility.getFullAXTree`. Hidden + non-interactive subtrees are
/// dropped during decode.
#[derive(Debug, Clone, Deserialize)]
pub struct RawAriaNode {
    pub role: String,
    #[serde(default)]
    pub name: String,
    #[serde(default)]
    pub value: Option<String>,
    /// Set to `true` for nodes that should be skipped (hidden, presentational).
    #[serde(default)]
    pub hidden: bool,
    /// Set to `true` for interactive nodes (buttons, links, inputs, etc.).
    /// Only interactive nodes get an `@eN` ref.
    #[serde(default)]
    pub interactive: bool,
    #[serde(default)]
    pub children: Vec<RawAriaNode>,
}

/// Decoder: walks a raw ARIA tree, mints `@e1..@eN` refs for interactive
/// nodes, and produces a compact text representation. Hidden / presentational
/// subtrees are pruned.
pub fn decode_snapshot(
    snapshot_id: u32,
    url: impl Into<String>,
    title: impl Into<String>,
    root: &RawAriaNode,
) -> AriaSnapshot {
    let mut nodes = Vec::new();
    let mut text = String::new();
    let mut counter: u32 = 0;
    walk(root, &mut nodes, &mut text, 0, &mut counter);
    AriaSnapshot {
        snapshot_id,
        url: url.into(),
        title: title.into(),
        nodes,
        text,
    }
}

fn walk(
    node: &RawAriaNode,
    out: &mut Vec<AriaNode>,
    text: &mut String,
    depth: usize,
    counter: &mut u32,
) {
    if node.hidden {
        return;
    }

    // Mint a ref ONLY for interactive nodes — keeps token count down.
    if node.interactive {
        *counter += 1;
        let r = ElementRef::new(format!("e{counter}"));
        // Compact line: "  @e3 button \"Submit\""  (indent = depth * 2 spaces).
        for _ in 0..depth {
            text.push_str("  ");
        }
        text.push_str(&r.display());
        text.push(' ');
        text.push_str(&node.role);
        if !node.name.is_empty() {
            text.push_str(" \"");
            text.push_str(&node.name);
            text.push('"');
        }
        if let Some(v) = &node.value
            && !v.is_empty()
        {
            text.push_str(" =");
            text.push_str(v);
        }
        text.push('\n');
        out.push(AriaNode {
            element_ref: r,
            role: node.role.clone(),
            name: node.name.clone(),
            value: node.value.clone(),
            children: Vec::new(),
        });
    } else if !node.name.is_empty() {
        // Non-interactive nodes with names still appear in the compact text
        // (for context) but without a ref.
        for _ in 0..depth {
            text.push_str("  ");
        }
        text.push_str(&node.role);
        text.push_str(" \"");
        text.push_str(&node.name);
        text.push_str("\"\n");
    }

    for child in &node.children {
        walk(child, out, text, depth + 1, counter);
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn fixture_tree() -> RawAriaNode {
        // Simulated DOM:
        //   main
        //     heading "Welcome"
        //     button "Sign in"
        //     button "Sign up"
        //     textbox name="email"
        //     [hidden] div
        //     link "Help"
        RawAriaNode {
            role: "main".into(),
            name: String::new(),
            value: None,
            hidden: false,
            interactive: false,
            children: vec![
                RawAriaNode {
                    role: "heading".into(),
                    name: "Welcome".into(),
                    value: None,
                    hidden: false,
                    interactive: false,
                    children: vec![],
                },
                RawAriaNode {
                    role: "button".into(),
                    name: "Sign in".into(),
                    value: None,
                    hidden: false,
                    interactive: true,
                    children: vec![],
                },
                RawAriaNode {
                    role: "button".into(),
                    name: "Sign up".into(),
                    value: None,
                    hidden: false,
                    interactive: true,
                    children: vec![],
                },
                RawAriaNode {
                    role: "textbox".into(),
                    name: "email".into(),
                    value: None,
                    hidden: false,
                    interactive: true,
                    children: vec![],
                },
                RawAriaNode {
                    role: "div".into(),
                    name: "should-not-appear".into(),
                    value: None,
                    hidden: true,
                    interactive: false,
                    children: vec![],
                },
                RawAriaNode {
                    role: "link".into(),
                    name: "Help".into(),
                    value: None,
                    hidden: false,
                    interactive: true,
                    children: vec![],
                },
            ],
        }
    }

    #[test]
    fn decode_mints_refs_in_order() {
        let snap = decode_snapshot(1, "https://example/", "Example", &fixture_tree());
        assert_eq!(snap.nodes.len(), 4);
        assert_eq!(snap.nodes[0].element_ref.as_str(), "e1");
        assert_eq!(snap.nodes[1].element_ref.as_str(), "e2");
        assert_eq!(snap.nodes[2].element_ref.as_str(), "e3");
        assert_eq!(snap.nodes[3].element_ref.as_str(), "e4");
        // Roles preserved.
        assert_eq!(snap.nodes[0].role, "button");
        assert_eq!(snap.nodes[2].role, "textbox");
        assert_eq!(snap.nodes[3].role, "link");
    }

    #[test]
    fn hidden_nodes_excluded_from_refs_and_text() {
        let snap = decode_snapshot(1, "https://x/", "x", &fixture_tree());
        assert!(!snap.text.contains("should-not-appear"));
        assert_eq!(snap.nodes.len(), 4);
    }

    #[test]
    fn resolve_returns_node_for_known_ref() {
        let snap = decode_snapshot(1, "https://x/", "x", &fixture_tree());
        let r = ElementRef::new("e2");
        let n = snap.resolve(&r).expect("ref @e2 should resolve");
        assert_eq!(n.name, "Sign up");
    }

    #[test]
    fn resolve_returns_none_for_unknown_ref() {
        let snap = decode_snapshot(1, "https://x/", "x", &fixture_tree());
        assert!(snap.resolve(&ElementRef::new("e99")).is_none());
    }

    #[test]
    fn snapshots_are_deterministic_across_decodes() {
        let a = decode_snapshot(1, "https://x/", "x", &fixture_tree());
        let b = decode_snapshot(1, "https://x/", "x", &fixture_tree());
        assert_eq!(a.text, b.text);
        let a_refs: Vec<_> = a.nodes.iter().map(|n| n.element_ref.as_str()).collect();
        let b_refs: Vec<_> = b.nodes.iter().map(|n| n.element_ref.as_str()).collect();
        assert_eq!(a_refs, b_refs);
    }

    #[test]
    fn element_ref_strips_at_prefix() {
        assert_eq!(ElementRef::new("@e7").as_str(), "e7");
        assert_eq!(ElementRef::new("e7").as_str(), "e7");
        assert_eq!(ElementRef::new("@e7").display(), "@e7");
    }
}
